// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgvmzvhysduhtuntxjho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndm16dmh5c2R1aHR1bnR4amhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwODA2MDAsImV4cCI6MjA5MDY1NjYwMH0.91RaUhtl-tTU-v_r85TJWXmPI_eO5f8d-fAbmKE3MD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});